name: CI Check on PR to Main

on:
    pull_request:
      branches: 
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 
      - name: Install dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --configuration Release --no-restore    