name: CI HR Leave Management Tests

on:
  push:
    branches:
      - main
      - feature
      - tests/*
  pull_request:
    branches:
      - main
      - feature
      - tests/*

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet restore ./HR.LeaveManagement.Core.sln

      - name: Build the solution
        run: dotnet build ./HR.LeaveManagement.Core.sln --configuration Release --no-restore

      - name: Debug Test Output Paths
        run: find . -type f      

      - name: Run unit tests with report
        run: dotnet test ./test/HR.LeaveManagement.Application.UnitTest/HR.LeaveManagement.Application.UnitTest.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"

      - name: Upload unit test results
        uses: actions/upload-artifact@v4
        with:
          name: UnitTestResults
          path: ./test/HR.LeaveManagement.Application.UnitTest/TestResults/TestResults.trx

      - name: Report Unit Test Results to GitHub UI
        uses: dorny/test-reporter@v1
        with:
          name: Unit Test Results
          path: ./test/HR.LeaveManagement.Application.UnitTest/TestResults/TestResults.trx
          reporter: dotnet-trx  # Use dotnet-trx parser
          fail-on-error: false  # Prevents workflow failure if file is missing

      - name: Run integration tests with report
        run: dotnet test ./test/HR.LeaveManagement.Persistence.IntegrationTests/HR.LeaveManagement.Persistence.IntegrationTests.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"
  
      - name: Upload integration test results
        uses: actions/upload-artifact@v4
        with:
          name: IntegrationTestResults
          path: ./test/HR.LeaveManagement.Persistence.IntegrationTests/TestResults/TestResults.trx

      - name: Report Integration Test Results to GitHub UI
        uses: dorny/test-reporter@v1
        with:
          name: Integration Test Results
          path: ./test/HR.LeaveManagement.Persistence.IntegrationTests/TestResults/TestResults.trx
          reporter: dotnet-trx
          fail-on-error: false
